version: '3.6'
services:
  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      # - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_data_conf:/etc/influxdb2

  grafana:
    image: grafana/grafana-oss:latest-ubuntu
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_data_plugins:/var/lib/grafana/plugins
      - grafana_data_logs:/var/log/grafana
  
  nodered:
    image: nodered/node-red:latest
    container_name: node-red
    restart: always
    depends_on:
      - influxdb
    ports:
      - '1880:1880'
    volumes:
      - node-red_data:/data

volumes:
  grafana_data:
  grafana_data_plugins:
  grafana_data_logs:
  influxdb_data:
  influxdb_data_conf:
  node-red_data: 
